import type { Project, Signal, Alert } from "./types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    name: "Ozempic Patient Experience",
    description: "Monitoring real-world evidence of side effects and treatment satisfaction for semaglutide users.",
    status: "Active",
    keywords: ["Ozempic", "Wegovy", "nausea", "weight loss", "shortage"],
    sources: ["X", "Reddit", "Forums"],
    stats: {
      signals7d: 1240,
      alerts: 12,
      avgSentiment: 68,
      trend: [20, 45, 30, 60, 50, 80, 75],
    },
    lastCrawl: "2024-05-06T10:30:00Z",
  },
  {
    id: "p2",
    name: "Keytruda Safety Signals",
    description: "Detecting early adverse event signals for immunotherapy patients across specialized oncology forums.",
    status: "Active",
    keywords: ["Keytruda", "immunotherapy", "fatigue", "rash", "pembrolizumab"],
    sources: ["Forums", "RSS", "Reddit"],
    stats: {
      signals7d: 450,
      alerts: 3,
      avgSentiment: 54,
      trend: [10, 15, 12, 18, 25, 22, 28],
    },
    lastCrawl: "2024-05-06T11:15:00Z",
  },
  {
    id: "p3",
    name: "Zepbound Launch Tracking",
    description: "Tracking market entry sentiment and accessibility issues for new obesity treatments.",
    status: "Paused",
    keywords: ["Zepbound", "Mounjaro", "insurance", "coverage", "availability"],
    sources: ["X", "Reddit"],
    stats: {
      signals7d: 890,
      alerts: 0,
      avgSentiment: 72,
      trend: [100, 90, 80, 70, 60, 50, 40],
    },
    lastCrawl: "2024-05-05T22:00:00Z",
  },
];

export const MOCK_SIGNALS: Signal[] = [
  {
    id: "s1",
    projectId: "p1",
    source: "Reddit",
    author: "u/health_warrior",
    content: "Has anyone else noticed severe nausea when switching from 0.5mg to 1mg of Ozempic? It's been 3 days and I can barely eat. Should I go back down or push through?",
    timestamp: "2024-05-06T09:45:00Z",
    sentiment: "Negative",
    sentimentScore: -0.85,
    confidence: 96,
    entities: [
      { text: "Ozempic", type: "Drug" },
      { text: "nausea", type: "Symptom" },
      { text: "1mg", type: "Dosage" },
    ],
    flags: ["Adverse Event", "Safety Signal"],
    matchedKeywords: ["Ozempic", "nausea"],
  },
  {
    id: "s2",
    projectId: "p1",
    source: "X",
    author: "@patient_advocate",
    content: "Finally got my Ozempic refill after 2 weeks of searching! The shortage is real, but so glad to be back on track. #OzempicShortage #HealthJourney",
    timestamp: "2024-05-06T08:15:00Z",
    sentiment: "Positive",
    sentimentScore: 0.65,
    confidence: 92,
    entities: [
      { text: "Ozempic", type: "Drug" },
      { text: "shortage", type: "Issue" },
    ],
    flags: [],
    matchedKeywords: ["Ozempic", "shortage"],
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "a1",
    severity: "Critical",
    source: "Reddit",
    keyword: "nausea",
    contentExcerpt: "Severe vomiting and dehydration reported after dosage increase...",
    signalType: "Adverse Event",
    confidence: 98,
    projectName: "Ozempic Patient Experience",
    timestamp: "2024-05-06T12:30:00Z",
    status: "Reviewing",
  },
  {
    id: "a2",
    severity: "High",
    source: "X",
    keyword: "shortage",
    contentExcerpt: "Cluster of 50+ mentions of pharmacies out of stock in NY area...",
    signalType: "Supply Chain",
    confidence: 94,
    projectName: "Zepbound Launch Tracking",
    timestamp: "2024-05-06T11:45:00Z",
    status: "Reviewing",
  },
  {
    id: "a3",
    severity: "Medium",
    source: "Forums",
    keyword: "rash",
    contentExcerpt: "Minor skin irritation reported by 3 users on same lot number...",
    signalType: "Adverse Event",
    confidence: 85,
    projectName: "Keytruda Safety Signals",
    timestamp: "2024-05-06T10:00:00Z",
    status: "Resolved",
  },
];
